name: Flutter

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v3
        with:
          channel: stable
          version: 3.22.3

      - name: Install dependencies
        run: flutter pub get
        working-directory: frontend

      - name: Create mock secret file
        run: |
          echo "class Secret {" > frontend/lib/api/secret.dart
          echo "  static const String hostUrl = '';" >> frontend/lib/api/secret.dart
          echo "  static const String authToken = '';" >> frontend/lib/api/secret.dart
          echo "}" >> frontend/lib/api/secret.dart
          
      - name: Analyze project source
        run: dart analyze
        working-directory: frontend
