name: Flutter

on:
  push:

env:
  flutter_version: "3.22.3"  # Update this to the desired version if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: ${{ env.flutter_version }}
      - run: flutter --version

      - name: Install dependencies
        run: flutter pub get
        working-directory: frontend

      - name: Create mock secret file
        run: |
          echo "class Secret {" > frontend/lib/secret.dart
          echo "  static const String hostUrl = '';" >> frontend/lib/secret.dart
          echo "  static const String authToken = '';" >> frontend/lib/secret.dart
          echo "}" >> frontend/lib/secret.dart

      - name: Analyze project source
        run: flutter analyze
        working-directory: frontend
