name: Flutter

on:
  push:

env:
  flutter_version: "3.22.3"  # Update this to the desired version if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Cache Flutter SDK
        id: cache-flutter-sdk
        uses: actions/cache@v3
        with:
          path: |
            ~/.flutter
          key: ${{ runner.os }}-flutter-${{ env.flutter_version }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: ${{ env.flutter_version }}

      - name: Verify Flutter version
        run: flutter --version

      - name: Cache Flutter packages
        id: cache-flutter-packages
        uses: actions/cache@v3
        with:
          path: |
            frontend/.pub-cache
            frontend/pubspec.lock
          key: ${{ runner.os }}-flutter-packages-${{ hashFiles('frontend/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-packages-

      - name: Install dependencies
        run: flutter pub get
        working-directory: frontend

      - name: Create mock secret file
        run: |
          echo "class Secret {" > frontend/lib/secret.dart
          echo "  static const String hostUrl = '';" >> frontend/lib/secret.dart
          echo "  static const String authToken = '';" >> frontend/lib/secret.dart
          echo "}" >> frontend/lib/secret.dart

      - name: Analyze project source
        run: flutter analyze
        working-directory: frontend

      - name: Build project
        run: flutter build
        working-directory: frontend

